[build]
  # Leave blank if package.json is in the root of your repo
  base = "" 
  
  # The command Next.js uses to build
  
  # For a standard Next.js build, use .next
  # If you use 'output: export' in next.config.js, change this to "out"
  command = "npm run build"
  publish = "out"